services:
  next-js:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next-js-frontend-infinity
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped